# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: dotto CI with gradle

on:
  push:
    branches: [back-end/master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: grant execute permission for gradlew
        run: chmod +x graldew
      - name : Build with gradle
        run: ./gradlew build
      - name: Docker build
        run: |
            docker build -t dotto-cicd:0.0.1 .
            docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            docker build -t spring-cicd:0.0.1 .
            docker tag dotto-cicd:0.0.1 yjh920127/dotto:${GITHUB_SHA::7}
            docker push yjh920127/dotto:${GITHUB_SHA::7}


